﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    public class ASysUserReq:BaseAEntityReq
    {
        /// <summary>
        /// 用户名
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string HeadImageUrl { get; set; }
        //public List<AdminRoleTop> adminRoleTops { get; set; }
        //public List<string> RoleIds { get; set; }

        public static implicit operator ASysUserReq(SysUser user)
        {
            return user.MapTo<ASysUserReq>();
        }
        public static implicit operator SysUser(ASysUserReq view)
        {
            return view.MapTo<SysUser>();
        }
        public ASysUserReq()
        { }
    }
    public class AdminRoleReq
    {
        /// <summary>
        /// 角色Id
        /// </summary>
        public string RoleId { get; set; }
        public static implicit operator AdminRoleReq(AdminRoleTop user)
        {
            return user.MapTo<AdminRoleReq>();
        }
        public static implicit operator AdminRoleTop(AdminRoleReq view)
        {
            return view.MapTo<AdminRoleTop>();
        }
        public AdminRoleReq()
        {
            this.RoleId = string.Empty;
        }
    }
}