﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    /// <summary>
    /// 修改管理员
    /// </summary>
    public class ESysUserReq:BaseEEntityReq
    {
        /// <summary>
        /// 用户名
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string HeadImageUrl { get; set; }
        //public List<AdminRoleTop> adminRoleTops { get; set; }
        // public List<EAdminRoleReq> adminRoleReqs { get; set; }
        //public List<string> RoleIds { get; set; }

        public static implicit operator ESysUserReq(SysUser user)
        {
            return user.MapTo<ESysUserReq>();
        }
        public static implicit operator SysUser(ESysUserReq view)
        {
            return view.MapTo<SysUser>();
        }
        public ESysUserReq()
        { }
    }
    public class EAdminRoleReq
    {
        /// <summary>
        /// 角色Id
        /// </summary>
        public string RoleId { get; set; }
        public static implicit operator EAdminRoleReq(AdminRoleTop user)
        {
            return user.MapTo<EAdminRoleReq>();
        }
        public static implicit operator AdminRoleTop(EAdminRoleReq view)
        {
            return view.MapTo<AdminRoleTop>();
        }
        public EAdminRoleReq()
        {
            this.RoleId = string.Empty;
        }
    }
}