﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    //public partial class SysOrgView:BaseViewReq
    //{
    //    /// <summary>
    //    /// 父级Id
    //    /// </summary>
    //    public string FatherId { get; set; }
    //    /// <summary>
    //    /// 组织名称
    //    /// </summary>
    //    public string Name { get; set; }
    //    /// <summary>
    //    /// 组织图标
    //    /// </summary>
    //    public string IconName { get; set; }

    //    public static implicit operator SysOrgView(SysOrg sysOrg)
    //    {
    //        return sysOrg.MapTo<SysOrgView>();
    //    }
    //    public static implicit operator SysOrg(SysOrgView view)
    //    {
    //        return view.MapTo<SysOrg>();
    //    }
    //    public SysOrgView()
    //    { }
    //}
}