//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using SysCommon.Repository.Core;

namespace SysCommon.Repository.Domain
{
    /// <summary>
	/// 公共字段管理
	/// </summary>
      [Table("CommonField")]
    public partial class CommonField : BaseEntity
    {
        public CommonField()
        {
            this.Placeholder = string.Empty;
            this.IsRequired = true;
            this.RequiredMessage = string.Empty;
            this.Size = 0;
            this.Columns = string.Empty;
            this.RegexPattern = string.Empty;
            this.RegexMessage = string.Empty;
            this.FieldOptions = null;
            this.AdditionalSettings = string.Empty;
            this.IsConfigAble = false;
            this.Name = string.Empty;
            this.PropertyName = string.Empty;
            this.DisplayName = string.Empty;
            this.Value = string.Empty;
            this.ValueArray = string.Empty;
        }

        [Description("占位符")]
        public string Placeholder { get; set ; }
        [Description("是否为必填")]
        public bool IsRequired { get ; set ; }
        [Description("必填说明")]
        public string RequiredMessage { get ; set; }
        [Description("")]
        public int Size { get ; set ; }
        [Description("")]
        public string Columns { get; set ; }
        [Description("正则表达")]
        public string RegexPattern { get; set ; }
        [Description("正则说明")]
        public string RegexMessage { get ; set ; }
        [Description("可选择字段")]
        public List<FieldOption> FieldOptions { get ; set ; }
        [Description("附加设置")]
        public string AdditionalSettings { get ; set ; }
        [Description("")]
        public bool IsConfigAble { get; set; }
        [Description("字段名称")]
        public string Name { get ; set ; }
        [Description("属性名称，即前台提交时设置的字段名称")]
        public string PropertyName { get ; set; }
        [Description("前台显示名称")]
        public string DisplayName { get ; set; }
        [Description("所存储的内容")]
        public string Value { get ; set; }
        [Description("")]
        public string ValueArray { get ; set ; }
    }
    public class FieldOption : BaseEntity
    {
        public string DisplayText { get; set; }
        private string _Value;
        public string Value
        {
            get
            {
                return _Value = Guid.NewGuid().ToString("N");
            }
            set { _Value = value; }
        }
    }
}