//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using SysCommon.Repository.Core;

namespace SysCommon.Repository.Domain
{
    /// <summary>
	/// 支付
	/// </summary>
      [Table("Payment")]
    public partial class Payment : BaseEntity
    {
        public Payment()
        {
            this.PayType = string.Empty;
            this.BuyerLogonId = string.Empty;
            this.TradeNo = string.Empty;
            this.TerminalId = string.Empty;
            this.TotalAmount = 0.00;
            this.StoreName = string.Empty;
            this.StoreId = string.Empty;
            this.SendPayDate = string.Empty;
            this.ReceiptAmount = string.Empty;
            this.PointAmount = string.Empty;
            this.TradeStatus = string.Empty;
            this.OutTradeNo = string.Empty;
            this.InvoiceAmount = 0;
            this.IndustrySepcDetail = string.Empty;
            this.AlipayStoreId = string.Empty;
            this.DiscountGoodsDetail = string.Empty;
            this.VoucherDetailList = string.Empty;
            this.BuyerPayAmount = 0.00;
            this.FundBillList = string.Empty;
            this.OpenId = string.Empty;
            this.BuyerUserId = string.Empty;
            this.Msg = string.Empty;
            this.ByUserType = string.Empty;
            this.PayState = false;
            this.RefundState = false;
            this.send_back_fee = 0.00;
            this.RefundNo = string.Empty;
        }

        [Description("退款单号")]
        public string RefundNo { get; set; }
        [Description("退款金额")]
        public double send_back_fee { get; set; }
        [Description("退款时间")]
        public DateTime? gmt_refund_pay { get; set; }
        [Description("退款状态")]
        public bool RefundState { get; set; }
        [Description("支付状态")]
        public bool PayState { get; set; }
        [Description("订单名称")]
        public string OrderName { get; set; }
        [Description("订单金额")]
        public string OrderAmount { get; set; }
        [Description("支付类型（支付宝、微信）")]
        public string PayType { get; set; }
        [Description("买家账号")]
        public string BuyerLogonId { get; set; }
        [Description("该交易在支付宝系统中的交易流水号，最长64位。")]
        public string TradeNo { get; set; }
        [Description("订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000]")]
        public double TotalAmount { get; set; }
        [Description("未定义")]
        public string TerminalId { get; set; }
        [Description("未定义")]
        public string StoreName { get; set; }
        [Description("商户门店编号")]
        public string StoreId { get; set; }
        [Description("未定义")]
        public string SendPayDate { get; set; }
        [Description("未定义")]
        public string ReceiptAmount { get; set; }
        [Description("未定义")]
        public string PointAmount { get; set; }
        [Description("未定义")]
        public string TradeStatus { get; set; }
        [Description("商户网站唯一订单号")]
        public string OutTradeNo { get; set; }
        [Description("发票金额")]
        public double InvoiceAmount { get; set; }
        [Description("未定义")]
        public string IndustrySepcDetail { get; set; }
        [Description("未定义")]
        public string FundBillList { get; set; }
        [Description("未定义")]
        public string DiscountGoodsDetail { get; set; }
        [Description("商户Id")]
        public string BuyerUserId { get; set; }
        [Description("支付金额")]
        public double BuyerPayAmount { get; set; }
        [Description("未定义")]
        public string AlipayStoreId { get; set; }
        [Description("未定义")]
        public string OpenId { get; set; }
        [Description("未定义")]
        public string VoucherDetailList { get; set; }
        [Description("支付结果")]
        public string Msg { get; set; }

        [Description("未定义")]
        public string ByUserType { get; set; }

    }
}