//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using SysCommon.Repository.Core;

namespace SysCommon.Repository.Domain
{
    /// <summary>
	/// 组织表
	/// </summary>
      [Table("Sys_Org")]
    public partial class SysOrg : BaseEntity
    {
        public SysOrg()
        {
          this.FatherId = string.Empty;
          this.Name= string.Empty;
          this.IconName = string.Empty;
        }
        /// <summary>
        /// 父级Id
        /// </summary>
        [Description("父级Id")]
        public string FatherId { get; set; }
        /// <summary>
        /// 组织名称
        /// </summary>
        [Description("组织名称")]
        public string Name { get; set; }
        /// <summary>
        /// 组织图标
        /// </summary>
        [Description("组织图标")]
        public string IconName { get; set; }

    }
}