//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using SysCommon.Repository.Core;

namespace SysCommon.Repository.Domain
{
    /// <summary>
	/// 角色表
	/// </summary>
    [Table("Sys_Role")]
    public partial class SysRole : BaseEntity
    {
        public SysRole()
        {
          this.Name= string.Empty;
        }

        /// <summary>
	    /// 角色名称
	    /// </summary>
        [Description("角色名称")]
        public string Name { get; set; }
    }
}