//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SysCommon.Repository.Core;

namespace SysCommon.Repository.Domain
{
    /// <summary>
	/// 管理员
	/// </summary>
      [Table("Sys_User")]
    public partial class SysUser : BaseEntity
    {
        public SysUser()
        {
            this.UserName = string.Empty;
            this.Password = "111111";
            this.Phone = string.Empty;
            this.Email = string.Empty;
            this.LoginCount = 0;
            this.LastLoginTime = DateTime.Now;
            this.HeadImageUrl = string.Empty;
        }
        [Description("用户名")]
        public string UserName { get; set; }
        [Description("密码")]
        public string Password { get; set; }
        [Description("电话")]
        public string Phone { get; set; }
        [Description("邮箱")]
        public string Email { get; set; }
        [Description("登录次数")]
        public int LoginCount { get; set; }
        [Description("最后登录时间")]
        public DateTime? LastLoginTime { get; set; }
        [Description("头像")]
        public string HeadImageUrl { get; set; }

    }
}