﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    public class AOECommonFieldReq
    {
        /// <summary>
        /// 字段Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 占位符
        /// </summary>
        public string Placeholder { get; set; }
        /// <summary>
        /// 是否为必填
        /// </summary>
        public bool IsRequired { get; set; }
        /// <summary>
        /// 必填说明
        /// </summary>
        public string RequiredMessage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Size { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Columns { get; set; }
        /// <summary>
        /// 正则表达
        /// </summary>
        public string RegexPattern { get; set; }
        /// <summary>
        /// 正则说明
        /// </summary>
        public string RegexMessage { get; set; }
        /// <summary>
        /// 可选择字段
        /// </summary>
        public List<FieldOption> FieldOptions { get; set; }
        /// <summary>
        /// 附加设置
        /// </summary>
        public string AdditionalSettings { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool IsConfigAble { get; set; }
        /// <summary>
        /// 字段名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 属性名称，即前台提交时设置的字段名称"
        /// </summary>
        public string PropertyName { get; set; }
        /// <summary>
        /// 前台显示名称
        /// </summary>
        public string DisplayName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Value { get; set; }
        /// <summary>
        /// 前台显示名称
        /// </summary>
        public string ValueArray { get; set; }


        public static implicit operator AOECommonFieldReq(CommonField article)
        {
            return article.MapTo<AOECommonFieldReq>();
        }
        public static implicit operator CommonField(AOECommonFieldReq view)
        {
            return view.MapTo<CommonField>();
        }
        public AOECommonFieldReq()
        { }
    }
}