﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    public class ContentReplaceReq
    {
        /// <summary>
        /// 数据表名称
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 字段名称
        /// </summary>
        public string FieldName { get; set; }
        /// <summary>
        /// 被替换数据
        /// </summary>
        public string OldContent { get; set; }
        /// <summary>
        /// 替换数据
        /// </summary>
        public string NewContent { get; set; }

        /// <summary>
        /// 创建人Id
        /// </summary>
        public string CreateId { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Description { get; set; }
        
        public static implicit operator ContentReplaceReq(ContentReplace contentReplace)
        {
            return contentReplace.MapTo<ContentReplaceReq>();
        }
        public static implicit operator ContentReplace(ContentReplaceReq view)
        {
            return view.MapTo<ContentReplace>();
        }
        public ContentReplaceReq()
        { }
    }
}