//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace SysCommon.Service.Request
{
    public class GetTableNameReq
    {

        /// <summary>
	    /// 数据表名称
	    /// </summary>
        public string TableName { get; set; }
    }
}