﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    public class RoleEditReq
    {
        /// <summary>
        /// 角色Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 角色名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 修改人
        /// </summary>
        public string UpdateId { get; set; }
        /// <summary>
        /// 是否启动
        /// </summary>
        public bool IsEnable { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        public static implicit operator RoleEditReq(SysUser user)
        {
            return user.MapTo<RoleEditReq>();
        }
        public static implicit operator SysRole(RoleEditReq view)
        {
            return view.MapTo<SysRole>();
        }
        public RoleEditReq()
        { }
    }
}