﻿//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using Infrastructure;
using SysCommon.Repository.Core;
using SysCommon.Repository.Domain;

namespace SysCommon.Service.Request
{
    public class UpdateAdminReq
    {
        /// <summary>
        /// 数据Id
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 修改人
        /// </summary>
        public string UpdateName { get; set; }
        /// <summary>
        /// 是否启动
        /// </summary>
        public bool IsEnable { get; set; }
        /// <summary>
        /// 排序 Description
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Description { get; set; }
        public List<AddSysUserRoleTopReq> addSysUserRoleTopReqs { get; set; }
        public static implicit operator UpdateAdminReq(SysUser user)
        {
            return user.MapTo<UpdateAdminReq>();
        }
        public static implicit operator SysUser(UpdateAdminReq view)
        {
            return view.MapTo<SysUser>();
        }
        public UpdateAdminReq()
        { }
    }
}